repository: jegra.github.io/ludwig
baseurl: '/ludwig'
imgbaseurl: 'https://ludwig-dev.imgix.net/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src/js
  - README.md
  - package.json
  - webpack.dev.js
  - webpack.prod.js
  - yarn.lock
permalink: pretty
title: 'Ludwig Tumor Atlas'

collections:
  pages:
    output: true
    permalink: /:path
  datasets:
    output: false

sass:
  sass_dir: src/_sass
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-seo-tag