repository: jegra.github.io/ludwig
baseurl: '/ludwig'
imgbaseurl: 'https://ludwig-dev.imgix.net/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src/js
  - README.md
  - package.json
  - webpack.dev.js
  - webpack.prod.js
  - yarn.lock
permalink: pretty
title: 'Ludwig Tumor Atlas'

collections:
  pages:
    output: true
    permalink: /:path
  datasets:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ''
      type: datasets
    values:
      section_id: data
      layout: summary
      heading: Data
      sub_heading: Data Summary
      wide_container: true
  - scope:
      path: ''
      type: projects
    values:
      section_id: projects
      layout: summary
      heading: Projects
      sub_heading: Project Summary
      summary_link_label: Project Summary
      wide_container: true


sass:
  sass_dir: src/_sass
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-seo-tag